{{- if .Values.console.hostname }}
apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: streams-console
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "kafka-broker.labels" . | nindent 4 }}
spec:
  hostname: {{ .Values.console.hostname | quote }}
  kafkaClusters:
    - name: {{ include "kafka-broker.name" . }}
      namespace: {{ .Values.namespace | default .Release.Namespace }}
      listener: plain
      credentials:
        kafkaUser:
          name: streams-console
          {{- if .Values.namespace }}
          namespace: {{ .Values.namespace }}
          {{- end }}
{{- end }}
