kafka-broker:
  console:
    hostname: ""
  authentication:
    securityProtocol: SASL_PLAINTEXT
    saslMechanism: SCRAM-SHA-512
    clientId: globex
    clientSecret: globex-scram-fips-password-32chars!
kafka-topics:
  kafka:
    namespace:
