nameOverride: "kafka"

kafka:
  enabled: true
  version: 4.1.0
  metadataVersion: 4.1-IV1
  kraft:
    poolName: pool
    replicas: 3
    resources:
      limits:
        cpu: '1'
        memory: 2G
      requests:
        cpu: 300m
        memory: 500M
  config:
    autoCreateTopics: false
    defaultReplicationFactor: 2
    offsetsTopicReplicationFactor: 2
    transactionStateLogReplicationFactor: 2
    transactionStateLogMinIsr: 2
    minInsyncReplicas: 1
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 500m
          memory: 500M
        requests:
          cpu: 250m
          memory: 250M
    userOperator:
      resources:
        limits:
          cpu: 250m
          memory: 250M
        requests:
          cpu: 150m
          memory: 150M

bootstrapServer: 

namespace:

authentication:
  clientId: ""
  clientSecret: ""
  securityProtocol: ""
  saslMechanism: ""

    #authorization: simple

argocd:
  enabled: true
  syncwave: "-2"
